services:
  db:
    image: postgres
    # set shared memory limit when using docker-compose
    shm_size: 128mb
    # or set shared memory limit when deploy via swarm stack
    #volumes:
    #  - type: tmpfs
    #    target: /dev/shm
    #    tmpfs:
    #      size: 134217728 # 128*2^20 bytes = 128Mb
    environment:
      POSTGRES_DB: "calendardb"
      POSTGRES_USER: "calendar"
      POSTGRES_PASSWORD: "calendar"  
      PGDATA: "/var/lib/postgresql/data/pgdata"
    volumes:
      - .:/docker-entrypoint-initdb.d
      - calendardb-data:/var/lib/postgresql/data
    ports:
      - 5432:5432
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U calendar -d calendardb"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
    restart: unless-stopped
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 4G

  rabbitmq:
    image: rabbitmq:3.10.7-management
    hostname: rabbitmq
    restart: always
    environment:
      - RABBITMQ_DEFAULT_USER=calendar
      - RABBITMQ_DEFAULT_PASS=calendarmq
    volumes:
      - rabbitmq-data:/var/lib/rabbitmq
    ports:
      - 15672:15672
      - 5672:5672
    healthcheck:
      test: rabbitmq-diagnostics -q ping
      interval: 30s
      timeout: 30s
      retries: 3

  calendar:
    image: otus15/calendar
    pull_policy: never
    build:
      context: ..
      dockerfile: build/Dockerfile
    ports:
      - 8080:8080
      - 8081:8081
    depends_on:
      db:
        condition: service_healthy

  sender:
    image: otus15/sender
    pull_policy: never
    build:
      context: ..
      dockerfile: build/Dockerfile.sender
    depends_on:
      db:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy

  scheduler:
    image: otus15/scheduler
    pull_policy: never
    build:
      context: ..
      dockerfile: build/Dockerfile.scheduler
    depends_on:
      db:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy

  integration:
    image: otus15/integration
    pull_policy: never
    build:
      context: ..
      dockerfile: build/Dockerfile.scheduler
    depends_on:
      - calendar
      - sender
      - scheduler

volumes:
  calendardb-data:
  rabbitmq-data:
