[logger]
level = "INFO"

[storage]
type = "SQL" # IM or SQL
connstr = "host=db user=calendar password=calendar dbname=calendardb sslmode=disable"

[rabbitmq]
connstr = "amqp://calendar:calendarmq@rabbitmq:5672/"
interval="2s"
KeepEvents="5h0m10s"
